services:
  - type: web
    name: wealth-estimator-api
    env: docker
    plan: free # Or "starter" for a paid plan that doesn't spin down
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: MODEL_CACHE_DIR
        value: /app/models
      - key: CHROMA_DB_PATH
        value: /app/chroma_db
    disks:
      - name: chroma-db-storage
        mountPath: /app/chroma_db
        sizeGB: 1
      - name: uploads-storage
        mountPath: /app/uploads
        sizeGB: 1
      - name: models-cache
        mountPath: /app/models
        sizeGB: 2 # Models can be large, so giving it more space
